server:
  port: 8081
spring:
  application:
    name: UserInfo-Service
  jpa:
    database: ORACLE
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: USERDB
    password: Tiger@123#

